name: ci/cd for git push 

on: 
  push: 
    branches: [ master ] 


jobs: 
  super-linter:
    name: Lint code and merge
    runs-on: ubuntu-latest   
    env: 
      FILTER_REGEX_EXCLUDE: ./*.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v4.10.1
        with:   
          excluded_files: /'README.md'
          files: ${{ join(github.event.push_request.changed_files, ',') }}       

        
        
        
  deploy: 
      runs-on: self-hosted   
      needs: [super-linter] 
      steps: 
        #- uses: actions/checkout@v2  #this is used for if you want to push all source code into runner       
        - name: update code base 
          working-directory: /var/www/html/team-pikachu-main-server 
          run: sudo git pull origin master        
        - name: restart   
          working-directory: /var/www/html/team-pikachu-main-server
          run: sudo systemctl restart nginx  
