name: Pull Request Accepted

on:
  pull_request:
    types: [closed]
    
jobs:
  on_accepted:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - name: update code base 
        working-directory: /var/www/html/team-pikachu-main-server 
        run: sudo git pull origin master        
      - name: restart   
        working-directory: /var/www/html/team-pikachu-main-server
        run: sudo systemctl restart nginx  
