name: CI/CD for pull request

on: 
  pull_request: 
    branches: [ master ]  
    
jobs: 
  super-linter:   
    runs-on: ubuntu-latest
    env: 
      FILTER_REGEX_EXCLUDE: ./*.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v4.10.1
        with:    
          files: ${{ join(github.event.pull_request.changed_files, ',') }}
          
  Merge:       
    runs-on: ubuntu-latest       
    needs: super-linter
    steps:   
      - name: Checkout Code 
        uses: actions/checkout@v2 
      - name: Merge pull requests 
        uses: pascalgn/automerge-action@v0.14.1
        with:   
          merge_method: squash
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}   
          
      
        

        
      
      
      
      
      
